
### PREPROCESS DATA YES/NO
PREPROCESS = True

### SIZE OF TRAIN-TEST-SPLIT
TEST_FRACTION = .2

## SIZE (no. of features) OF INPUT AND OUTPUT
INPUT_SIZE = 34
HIDDEN_SIZE = 300
OUTPUT_SIZE = 5

## TRAINING HYPERPARAMS
LEARNING_RATE = 1e-4
NUM_EPOCHS = 300