
### RANDOM SEED
SEED = 100

### PREPROCESS DATA YES/NO
PREPROCESS = True
UPSAMPLING = True
# Upsampling type - random or SMOTE
UPSAMPLING_TYPE = "random" 

### SIZE OF TRAIN-TEST-SPLIT
TEST_FRACTION = .2

### NUMBER OF FOLDS FOR CROSS-VALIDATION
K_FOLDS = 5

## SIZE (no. of features) OF INPUT AND OUTPUT
if PREPROCESS:
    INPUT_SIZE = 34
else:
    INPUT_SIZE = 33
HIDDEN_SIZE = 300
OUTPUT_SIZE = 5

PMF_LAYER = True
if PMF_LAYER:
    PMF_TYPE = 'Poisson' # One of 'Poisson', 'Bernoulli'

## TRAINING HYPERPARAMS
LEARNING_RATE = 1e-3
NUM_EPOCHS = 500